name: ascii-draw 
base: core24 
adopt-info: ascii-draw
grade: stable 
confinement: strict
platforms:
  amd64:
  arm64:

parts:
  python-deps:
    source: .
# ext:updatesnap
#   version-format:
#     ignore: true
    plugin: python
    python-packages:
      - emoji==2.8.0
      - pyfiglet==0.8.post1 
    prime:
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -pyvenv.cfg
      - -usr/lib/*/site-packages/gi
      - -usr/lib/*/site-packages/pygtkcompat
      - -usr/lib/*/site-packages/PyG*
      - -usr/lib/*/site-packages/pycairo*
      - -usr/lib/*/site-packages/cairo*
      - -usr/lib/*/*/setup*
      - -usr/lib/*/*/pkg*
      - -usr/lib/*/*/pip*
      - -usr/lib/*/*/_dist*
      - -share
      - -include
    organize:
      bin: usr/bin
      lib/python3.12/site-packages: usr/lib/python3/dist-packages

  ascii-draw:
    after: [ python-deps ]
    plugin: meson
    source: https://github.com/Nokse22/ascii-draw.git
    source-tag: 'v0.4.0'
    source-depth: 1
    parse-info: [ usr/share/metainfo/io.github.nokse22.asciidraw.metainfo.xml ]
    build-snaps:
      - blueprint-compiler/latest/edge
    meson-parameters:
      - --prefix=/snap/ascii-draw/current/usr
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/ascii-draw/current/usr/bin/ascii-draw
      chmod +x $CRAFT_PART_INSTALL/snap/ascii-draw/current/usr/bin/ascii-draw
    organize:
      snap/ascii-draw/current: .

slots:
  ascii-draw:
    interface: dbus
    bus: session
    name: io.github.nokse22.asciidraw

apps:
  ascii-draw:
    command: usr/bin/ascii-draw
    extensions: [ gnome ]
    common-id: io.github.nokse22.asciidraw
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    desktop: usr/share/applications/io.github.nokse22.asciidraw.desktop
